### ISSUE TITLE
Project Topic Proposal

### ISSUE THREAD

**Issue by chuangw6** [UBC-MDS/eda_utils_py#1]

**Comment by micahkwok** [comment]
An idea would be an EDA package that would take in a dataframe. Functions could include but not be limited to: 

- plotting (I feel like I'm constantly re-writing simple plot code so could be a useful function)
- imputation
- correlation

**Comment by fatse** [comment]
I think it would be useful to create a package that after we fit/train an ML model we can feed that model to a function that will:

- render training/validation accuracy, training/validation fitting time in a nice table, e.g. a pandas dataframe
- show different metrics, such as recall, precision, f1-score 
- confusion matrix
- feature importance

**Comment by chuangw6** [comment]
Discussion from the team meeting:
- function 1: to deal with missing values, outliers etc. (imputation; maybe another separate function for summarizing the missing data)
- function 2: to identify different types of features e.g. numerical, categorical, ordinal etc.
- function 3: to OHE / scaling
- function 4: to plot numerical features

**Comment by micahkwok** [comment]
Feedback from TA 
- Function 1: **imputing missing values** - is a good function to implement
- Function 2: **identify types of features** - is too simple and needs to be changed
- Function 3: **scaling**  - good as long as we implement it ourselves instead of doing something like call standardScaler()
- Function 4: **plot numerical features** - instead of a histogram we could do plots that show correlation instead, as he said histograms are too simple

Suggested Function
- Function 2 replacement: **A function to detect and/or deal with outliers**

Overall guidelines on functions
- functions should not simply call an existing function (ie our scaling function simply calling standardscaler())
- don't make overly complicated codes as you need to implement this in both Python and R, it is recommended that the actual code portion (so excluding variable assignments etc.) to be 10 lines long

We should decide on who is responsible for each function.

**Comment by fatse** [comment]
Closing this as we decided about the package topic on Thursday.
